# Also runnable with cmake -P, without configuring or compiling the application.
get_filename_component(_notice_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_notice_manifest "${_notice_root}/third_party/wellen-licenses/manifest.json")
set(_notice_lock "${_notice_root}/tools/wellen_reader/Cargo.lock")
if(NOT CMAKE_SCRIPT_MODE_FILE)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
        "${_notice_lock}" "${_notice_manifest}")
endif()
file(READ "${_notice_lock}" _notice_lock_text)
string(REPLACE "\r\n" "\n" _notice_lock_text "${_notice_lock_text}")
string(SHA256 _notice_lock_sha "${_notice_lock_text}")
file(READ "${_notice_manifest}" _notice_inventory)
string(JSON _notice_expected_lock GET "${_notice_inventory}" cargoLockSha256Lf)
if(NOT _notice_lock_sha STREQUAL _notice_expected_lock)
    message(FATAL_ERROR "Cargo.lock changed: regenerate and review notices with scripts/collect-wellen-licenses.py")
endif()
string(JSON _notice_package_count LENGTH "${_notice_inventory}" packages)
if(_notice_package_count LESS 1)
    message(FATAL_ERROR "The Wellen dependency notice inventory is empty")
endif()
math(EXPR _notice_last_package "${_notice_package_count} - 1")
foreach(_notice_package RANGE 0 ${_notice_last_package})
    string(JSON _notice_file_count LENGTH "${_notice_inventory}" packages ${_notice_package} files)
    if(_notice_file_count LESS 1)
        message(FATAL_ERROR "A Wellen dependency has no retained license text")
    endif()
    math(EXPR _notice_last_file "${_notice_file_count} - 1")
    foreach(_notice_file RANGE 0 ${_notice_last_file})
        string(JSON _notice_path GET "${_notice_inventory}" packages ${_notice_package} files ${_notice_file} path)
        string(JSON _notice_expected_sha GET "${_notice_inventory}" packages ${_notice_package} files ${_notice_file} sha256Lf)
        file(READ "${_notice_root}/third_party/wellen-licenses/${_notice_path}" _notice_text)
        string(REPLACE "\r\n" "\n" _notice_text "${_notice_text}")
        string(SHA256 _notice_sha "${_notice_text}")
        if(NOT _notice_sha STREQUAL _notice_expected_sha)
            message(FATAL_ERROR "Wellen license missing or changed: ${_notice_path}")
        endif()
    endforeach()
endforeach()
message(STATUS "Verified notices for ${_notice_package_count} locked Rust packages")
